from backend.config import app as _app
from backend.config import auth as _auth
from backend.config import community as _community
from backend.config import loop as _loop
from backend.config import model as _model
from backend.config import paths as _paths
from backend.config import skill as _skill


APP_NAME = _app.APP_NAME
ATTACHMENT_MAX_BYTES = _app.ATTACHMENT_MAX_BYTES
CORS_ALLOW_ORIGINS = _app.CORS_ALLOW_ORIGINS
LOG_LEVEL = _app.LOG_LEVEL
LOG_REQUESTS = _app.LOG_REQUESTS

ACCESS_TOKEN_EXPIRE_MINUTES = _auth.ACCESS_TOKEN_EXPIRE_MINUTES
JWT_ALGORITHM = _auth.JWT_ALGORITHM
JWT_SECRET = _auth.JWT_SECRET
NONCE_CLEANUP_PROBABILITY = _auth.NONCE_CLEANUP_PROBABILITY
NONCE_EXPIRY_SECONDS = _auth.NONCE_EXPIRY_SECONDS
REFRESH_COOKIE_NAME = _auth.REFRESH_COOKIE_NAME
REFRESH_COOKIE_PATH = _auth.REFRESH_COOKIE_PATH
REFRESH_COOKIE_SAMESITE = _auth.REFRESH_COOKIE_SAMESITE
REFRESH_COOKIE_SECURE = _auth.REFRESH_COOKIE_SECURE
REFRESH_TOKEN_EXPIRE_DAYS = _auth.REFRESH_TOKEN_EXPIRE_DAYS

PAGE_DEFAULT_LIMIT = _community.PAGE_DEFAULT_LIMIT
PAGE_MAX_LIMIT = _community.PAGE_MAX_LIMIT
SORT_DEFAULT = _community.SORT_DEFAULT
SORTS = _community.SORTS
CommunitySkillSort = _community.CommunitySkillSort

LOOP_MAX_RETRIES = _loop.LOOP_MAX_RETRIES

GetAgent = _model.GetAgent
GetProvider = _model.GetProvider
INSTRUCTION = _model.INSTRUCTION
INSTUCTION = _model.INSTRUCTION  # compat alias
load_instruction = _model.load_instruction
load_prompt = _model.load_prompt
MODEL_BASE_URL = _model.MODEL_BASE_URL
MODEL_NAME = _model.MODEL_NAME
MODEL_PROVIDER_API_KEY = _model.MODEL_PROVIDER_API_KEY

BASE_DIR = _paths.BASE_DIR
DATABASE_PATH = _paths.DATABASE_PATH
SKILL_STORAGE_DIR = _paths.SKILL_STORAGE_DIR

COMPATIBILITY_MAX = _skill.COMPATIBILITY_MAX
DESCRIPTION_MAX = _skill.DESCRIPTION_MAX
DISPLAY_NAME_MAX = _skill.DISPLAY_NAME_MAX
SKILL_NAME_MAX = _skill.SKILL_NAME_MAX
SKILL_NAME_PATTERN = _skill.SKILL_NAME_PATTERN
SKILL_NAME_RE = _skill.SKILL_NAME_RE
SKILL_RESERVED = _skill.SKILL_RESERVED
SKILL_RESOURCE_DIRS = _skill.SKILL_RESOURCE_DIRS
SKILL_TEXT_EXTENSIONS = _skill.SKILL_TEXT_EXTENSIONS
SKILL_FILE_MAX_CHARS = _skill.SKILL_FILE_MAX_CHARS
SKILL_ZIP_ALLOWED_CONTENT_TYPES = _skill.SKILL_ZIP_ALLOWED_CONTENT_TYPES
SKILL_ZIP_MAX_BYTES = _skill.SKILL_ZIP_MAX_BYTES
SKILL_ZIP_RESOURCE_DIR_ALIASES = _skill.SKILL_ZIP_RESOURCE_DIR_ALIASES
validate_skill_name = _skill.validate_skill_name

__all__ = [
    "ACCESS_TOKEN_EXPIRE_MINUTES",
    "APP_NAME",
    "ATTACHMENT_MAX_BYTES",
    "BASE_DIR",
    "COMPATIBILITY_MAX",
    "CORS_ALLOW_ORIGINS",
    "DATABASE_PATH",
    "DESCRIPTION_MAX",
    "DISPLAY_NAME_MAX",
    "GetAgent",
    "GetProvider",
    "INSTRUCTION",
    "INSTUCTION",
    "load_instruction",
    "load_prompt",
    "JWT_ALGORITHM",
    "JWT_SECRET",
    "LOG_LEVEL",
    "LOG_REQUESTS",
    "LOOP_MAX_RETRIES",
    "MODEL_BASE_URL",
    "MODEL_NAME",
    "MODEL_PROVIDER_API_KEY",
    "NONCE_CLEANUP_PROBABILITY",
    "NONCE_EXPIRY_SECONDS",
    "REFRESH_COOKIE_NAME",
    "REFRESH_COOKIE_PATH",
    "REFRESH_COOKIE_SAMESITE",
    "REFRESH_COOKIE_SECURE",
    "REFRESH_TOKEN_EXPIRE_DAYS",
    "PAGE_DEFAULT_LIMIT",
    "PAGE_MAX_LIMIT",
    "SKILL_NAME_MAX",
    "SKILL_NAME_PATTERN",
    "SKILL_NAME_RE",
    "SKILL_RESERVED",
    "SKILL_RESOURCE_DIRS",
    "SKILL_STORAGE_DIR",
    "SKILL_TEXT_EXTENSIONS",
    "SKILL_FILE_MAX_CHARS",
    "SKILL_ZIP_ALLOWED_CONTENT_TYPES",
    "SKILL_ZIP_MAX_BYTES",
    "SKILL_ZIP_RESOURCE_DIR_ALIASES",
    "SORT_DEFAULT",
    "SORTS",
    "CommunitySkillSort",
    "validate_skill_name",
]
